env: flex
runtime: nodejs

env_variables:
  NODE_ENV: "development"
  DEBUG: "app:dev"
  JWT_SECRET: "isntsofteng2fun"
  DB_PREFIX: "mongodb://"
  DB_USER: "dev"
  DB_PASS: "dev"
  DB_HOST: "@favour-trader-dev-shard-00-00-apfb7.mongodb.net:27017,favour-trader-dev-shard-00-01-apfb7.mongodb.net:27017,favour-trader-dev-shard-00-02-apfb7.mongodb.net:27017/test?ssl=true&replicaSet=Favour-Trader-Dev-shard-0&authSource=admin"
  DB_SEED: "false"
  TEST_DB_USER: "admin"
  TEST_DB_PASS: "admin"
  TEST_DB_HOST: "@favour-trader-test-shard-00-00-oulfu.mongodb.net:27017,favour-trader-test-shard-00-01-oulfu.mongodb.net:27017,favour-trader-test-shard-00-02-oulfu.mongodb.net:27017/test?ssl=true&replicaSet=favour-Trader-test-shard-0&authSource=admin"